/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#2a273e",
        "on-background": "#e5defe",
        "error": "#ffb4ab",
        "surface-dim": "#131027",
        "on-tertiary-fixed-variant": "#8f0044",
        "error-container": "#93000a",
        "primary-fixed-dim": "#c7c0f8",
        "secondary": "#d3fbff",
        "on-secondary": "#00363a",
        "on-error": "#690005",
        "primary-fixed": "#e4dfff",
        "primary-container": "#1a1442",
        "inverse-primary": "#5e588a",
        "inverse-on-surface": "#312d45",
        "surface-container-low": "#1c192f",
        "tertiary": "#ffb1c4",
        "tertiary-container": "#3e001a",
        "on-tertiary-fixed": "#3f001a",
        "surface-variant": "#35324a",
        "on-primary-container": "#847eb2",
        "secondary-fixed": "#7df4ff",
        "secondary-container": "#00eefc",
        "on-surface-variant": "#c9c5d0",
        "surface-tint": "#c7c0f8",
        "on-secondary-fixed-variant": "#004f54",
        "outline-variant": "#47464f",
        "on-surface": "#e5defe",
        "on-primary-fixed-variant": "#464170",
        "on-tertiary": "#65002e",
        "on-primary-fixed": "#1a1442",
        "tertiary-fixed-dim": "#ffb1c4",
        "on-primary": "#2f2a58",
        "surface-bright": "#3a364e",
        "on-error-container": "#ffdad6",
        "surface": "#131027",
        "outline": "#928f99",
        "on-tertiary-container": "#ff027f",
        "tertiary-fixed": "#ffd9e1",
        "background": "#131027",
        "on-secondary-fixed": "#002022",
        "inverse-surface": "#e5defe",
        "surface-container-lowest": "#0e0b21",
        "secondary-fixed-dim": "#00dbe9",
        "surface-container": "#201d33",
        "surface-container-highest": "#35324a",
        "on-secondary-container": "#00686f",
        "primary": "#c7c0f8",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "space-sm": "0.5rem",
        "space-base": "1rem",
        "space-xs": "0.25rem",
        "space-2xl": "3rem",
        "space-xxs": "0.125rem",
        "space-xl": "2rem",
        "space-md": "0.75rem",
        "margin-desktop": "2rem",
        "margin-mobile": "1rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
      },
      fontFamily: {
        "display-hero-mobile": ["Sora", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "display-hero": ["Sora", "sans-serif"],
        "headline-sm": ["Sora", "sans-serif"],
        "label-lg": ["Geist", "sans-serif"],
        "label-code": ["Geist", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "display-hero-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-hero": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-code": ["11px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "500" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};